name: Manual Profile Updater

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v4

      - name: Setting up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          architecture: "x64"
          cache: "pip"

      - name: Running Scripts
        run: |
          pip install -r requirements.txt
          python tendencia.py
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Actualizar perfil"
          git push
